config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'members#index'
  resources :cards
  resources :members do
    post :buy
  end
  resources :musics do
    post :buy
  end
  resources :decks do
    post :remove_member
    post :remove_music
    post :to_start
    post :draw, on: :collection
    post :back, on: :collection
    post :enter, on: :collection
    post :enter_from_top, on: :collection
    post :to_top, on: :collection
    post :to_bottom, on: :collection
    post :setlist_open, on: :collection
    post :live, on: :collection
    member do
      get :battle
      get :display
    end
  end

  post "/members/:id", to: "decks#add"
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :card, foreign_key: :number, primary_key: :number
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= form_for(music) do |f| %>
  <% if music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Musics</h1>

<%= form_for @search_form, as: 'search', url: :musics, html: {method: :get, class: "form-inline"} do |f| %>
  <div class="form-group">
    <%= f.label :select, "すべて表示" %>
    <%= f.radio_button :select, :all, :checked => true , class: "radio" %>
  </div>

  <div class="form-group">
    <%= f.label :select, "共通スコア" %>
    <%= f.radio_button :select, :score_common, class: "radio" %>
  </div>

  <%= f.submit "検索", class: "btn btn-primary" %>
  </div>
<% end %>

<%= page_entries_info @musics %>
<br>

<div>
  <% @musics.each do |music| %>
    <div style="display:inline-block;vertical-align:top;width:200px;" >
      <%= link_to music do %>
        <div><img src=<%= music.img %>></div>
        <div><%= music.number%> <%= music.name %></div>
      <% end %>
      <%= form_tag music_buy_path(:music_id => music.id, :music_number => music.number), :action => :buy, :remote => true do %>
        <%= select_tag :number, options_for_select(["0", "1"]) %>
        <%= submit_tag "デッキに追加", class: "btn btn-success" %>
      <% end %>
    </div>
  <% end %>
</div>

<%= will_paginate @musics, :renderer => BootstrapPagination::Rails %>
<br>

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<img src=<%= @music.img %>>

<p>
  <strong>カードID</strong>
  <%= @music.number%>
</p>

<p>
  <strong>カード名</strong>
  <%= @music.name%>
</p>

<p>
  <strong>フレーバーテキスト</strong>
  <%= @music.skill%>
</p>

<%= link_to 'Back', musics_path %>