config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'members#index'
  resources :cards
  resources :members do
    post :buy
  end
  resources :musics do
    post :buy
  end
  resources :decks do
    post :remove_member
    post :remove_music
    post :to_start
    post :draw, on: :collection
    post :back, on: :collection
    post :enter, on: :collection
    post :enter_from_top, on: :collection
    post :to_top, on: :collection
    post :to_bottom, on: :collection
    post :setlist_open, on: :collection
    post :live, on: :collection
    member do
      get :battle
      get :display
    end
  end

  post "/members/:id", to: "decks#add"
end

app/models/deck.rb
class Deck < ApplicationRecord
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy, :battle, :to_start, :display]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all.order(:id)

    @members= []
    @musics= []

    begin
      session[:member].each do |member|
        id = member[0]
        count = member[1]

        count.to_i.times do
          @members << Member.joins(:card).select("cards.*, members.*").find_by(number: id) 
        end
      end
    rescue
      # do nothing
    end

    begin
      session[:music].each do |music|
        id = music[0]
        count = music[1]

        count.to_i.times do
          @musics << Music.joins(:card).select("cards.*, musics.*").find_by(number: id) 
        end
      end
    rescue
      # do nothing
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  def display
  end

  # GET /decks/1/battle
  def battle
    # === セッション情報の初期化 ===
    # 待機中メンバー = スタートメンバー
    session[:waiting] = [@start.id]

    # 手札
    session[:deck] = @members.shuffle.map {|member| member.id }
    session[:hand] = session[:deck].pop(4)
    
    # セットリスト
    session[:setlist_closed] = @musics.shuffle.map {|music| music.id }
    session[:setlist_open] = session[:setlist_closed].pop(2)

    # ライブ中
    session[:live] = []

    self.rendering
  end

  # デッキからカード1ドロー
  def draw
    session[:hand] <<  session[:deck].pop if session[:deck].length > 0
    self.rendering
  end

  # 登場
  def enter
    session[:waiting] << session[:hand].delete_at(params[:index].to_i)
    self.rendering
  end

  # 登場
  def enter_from_top
    session[:waiting] << session[:deck].pop if session[:deck].length > 0
    self.rendering
  end

  # 手札をデッキの一番上に置く
  def to_top
    session[:deck] << session[:hand].delete_at(params[:index].to_i)
    self.rendering
  end

  # 手札をデッキの一番下に置く
  def to_bottom
    # ボトムすなわちデッキ配列の先頭に追加
    session[:deck].unshift(session[:hand].delete_at(params[:index].to_i))
    self.rendering
  end

  # セットリストオープン 
  def setlist_open
    session[:setlist_open] << session[:setlist_closed].pop if session[:setlist_closed].length > 0
    self.rendering
  end

  # セットリストオープン 
  def back
    session[:hand] << session[:waiting].delete_at(params[:index].to_i)
    self.rendering
  end

  # ライブする
  def live
    music = ""
    members = []

    music = session[:setlist_open].delete_at(params[:music].to_i)
    params[:member][:index].sort {|x, y| y.to_i <=> x.to_i }.each do |index|
      members << session[:waiting].delete_at(index.to_i)
    end
    session[:setlist_open] << session[:setlist_closed].pop if session[:setlist_closed].length > 0

    live = [music, members]
    session[:live] << live

    self.rendering
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
    session[:member] = Hash.new(0)
    session[:music] = Hash.new(0)

    session[:member][@start.number] += 1
    @members.each do |member|
      session[:member][member.number] += 1
    end
    @musics.each do |music|
      session[:music][music.number] += 1
    end
    redirect_to decks_url
  end

  # POST /decks
  # POST /decks.json
  def create
    memberlist_id = Memberlist.maximum(:memberlist_id)
    if memberlist_id.nil?
        memberlist_id = 1
    else
      memberlist_id += 1
    end

    setlist_id = Setlist.maximum(:setlist_id)
    if setlist_id.nil?
        setlist_id = 1
    else
      setlist_id += 1
    end

    # memberlist, setlistの作成
    session[:member].each do |member|
      id = member[0]
      p count = member[1]
      start = ( Memberlist.find_by(memberlist_id: memberlist_id).present? ? false : true )
      Memberlist.new(memberlist_id: memberlist_id, number: id, count: count, start: start).save
    end
    session[:music].each do |music|
      id = music[0]
      count = music[1]
      Setlist.new(setlist_id: setlist_id, number: id, count: count).save
    end

    # デッキの作成
    @deck = Deck.new(name: params[:name], memberlist_id: memberlist_id, setlist_id: setlist_id)

    # セッション情報の削除
    session[:member].clear
    session[:music].clear

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_member
    session[:member][params[:member_number]] -= 1
    pp session[:member]
  end

  def remove_music
    session[:music][params[:music_number]] -= 1
    pp session[:music]
  end

  def to_start
    memberlist_id = Deck.find(params[:deck_id]).memberlist_id
    Memberlist.find_by(memberlist_id: memberlist_id, start: true).update(start: false)
    Memberlist.find_by(memberlist_id: memberlist_id, number: params[:number]).update(start: true)

    redirect_to @deck
  end

  def rendering
    # === セッション情報を基に画面に表示するカード情報を取得 ===
    @waiting = session[:waiting].map {|id| Member.joins(:card).select("cards.*, members.*").find(id) }
    @hands = session[:hand].map {|id| Member.joins(:card).select("cards.*, members.*").find(id) }
    @setlist_open = session[:setlist_open].map {|id| Music.joins(:card).select("cards.*, musics.*").find(id) }
    @live = session[:live].map {|elem| 
      [Music.joins(:card).select("cards.*, musics.*").find(elem[0]), elem[1].map {|id| 
        Member.joins(:card).select("cards.*, members.*").find(id) 
      }]
    }
    @live ||= [] 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
      memberlist = Memberlist.where(memberlist_id: @deck.memberlist_id)

      start = Memberlist.find_by(memberlist_id: @deck.memberlist_id, start: true)
      @start = Member.joins(:card).select("cards.*, members.*").find_by(number: start.number)
      @members = []
      @musics = []
      memberlist.each do |member|
        # スタートメンバーはデッキから-1枚する
        count = member.count.to_i
        count -= 1 if member.number == @start.number

        count.times do
          @members << Member.joins(:card).select("cards.*, members.*").find_by(number: member.number)
        end
      end

      setlist = Setlist.where(setlist_id: @deck.setlist_id)
      setlist.each do |music|
        music.count.to_i.times do
          @musics << Music.joins(:card).select("cards.*, musics.*").find_by(number: music.number)
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.fetch(:deck, {})
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for(deck) do |f| %>
  <% if deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/_stage.html.erb
<%= form_tag live_decks_path, remote: true do %>
    <h1>ライブ中</h1>
    <div>
      <% @live.each do |live| %>
        <div style="display:inline-block;vertical-align:top;width:200px;" >
          <div><img src=<%= live[0].img %>></div>
          <div><%= live[0].number %> <%= live[0].name %></div>
        </div>

        <% live[1].each_index do |index| %>
          <div style="display:inline-block;vertical-align:top;width:175px;" >
            <div><img src=<%= live[1][index].img %>></div>
            <div><%= live[1][index].number %> <%= live[1][index].name %></div>
          </div>
        <% end %>
        <br>
      <% end %>
    </div>

    <h1>待機中</h1>
    <div>
      <% @waiting.each_index do |index| %>
        <div style="display:inline-block;vertical-align:top;width:175px;" >
          <div><img src=<%= @waiting[index].img %>></div>
          <div><%= @waiting[index].number %> <%= @waiting[index].name %></div>
          <div style="padding-left:60px">
            <%= check_box_tag "member[index][]", index, checked = false, class: "checkbox" %>
          </div>
          <br>
          <div><%= link_to '手札に戻す', back_decks_path(index: index), method: :post, remote: true, class: "btn btn-default" %></div>
        </div>
      <% end %>
    </div>

  <div class="row">
    <div class="col-xs-3 col-md-2">
      <h1>セットリスト</h1>
      <%= link_to 'セットリストオープン', setlist_open_decks_path, method: :post, remote: true, type: :button, class: "btn btn-default" %>
      <div>
        <% @setlist_open.each_index do |index| %>
          <div style="display:inline-block;vertical-align:top;width:200px;" >
            <div><img src=<%= @setlist_open[index].img %>></div>
            <div><%= @setlist_open[index].number %> <%= @setlist_open[index].name %></div>
            <div align="center">
              <%= radio_button_tag "music", index, class: "checkbox" %>
            </div>
          </div>
        <% end %>
      </div>
      <div align="center">
        <%= submit_tag "ライブする", class: "btn btn-default" %>
      </div>
    </div>
<% end %>

<div class="col-xs-9 col-md-10">
  <h1>手札・山札</h1>
  <h3>山札:<%= session[:deck].length %>枚</h3>
  <div class="row">
    <div class="col-xs-3 col-md-2">
      <%= link_to 'デッキトップ登場', enter_from_top_decks_path, method: :post, remote: true, type: :button ,class: "btn btn-default" %>
    </div>
    <div class="col-xs-3 col-md-2">
      <%= link_to '1ドロー', draw_decks_path, method: :post, remote: true, type: :button, class: "btn btn-default" %>
    </div>
  </div>
  <br>
  <div>
    <% @hands.each_index do |index| %>
      <div style="display:inline-block;vertical-align:top;width:175px;" >
        <div style="padding-left:40px"><%= link_to '登場', enter_decks_path(index: index), method: :post, remote: true, type: :button, class: "btn btn-default" %></div>
        <div><img src=<%= @hands[index].img %>></div>
        <div><%= @hands[index].number %> <%= @hands[index].name %></div>
        <div class="row">
          <div class="col-xs-6">
            <div><%= link_to 'ボトム', to_bottom_decks_path(index: index), method: :post, remote: true, type: :button, class: "btn btn-warning" %></div>
          </div>
          <div class="col-xs-6">
            <div><%= link_to 'トップ', to_top_decks_path(index: index), method: :post, remote: true, type: :button, class: "btn btn-warning" %></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

</div>

app/views/decks/back.js.erb
$("#stage").html( '<%= j(render 'stage') %>');

app/views/decks/battle.html.erb
<div id="stage">
  <%= render "stage" %>
</div>

app/views/decks/draw.js.erb
$("#stage").html( '<%= j(render 'stage') %>');

app/views/decks/enter.js.erb
$("#stage").html( '<%= j(render 'stage') %>');

app/views/decks/enter_from_top.js.erb
$("#stage").html( '<%= j(render 'stage') %>');

app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Decks</h1> <table class="table table-striped">
  <thead>
    <tr>
      <th>デッキ名</th>
      <th>デッキID</th>
      <th>セットリストID</th>
  </thead>
  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= deck.memberlist_id %></td>
        <td><%= deck.setlist_id %></td>
        <td><%= link_to "show", deck %></td>
        <td><%= link_to "destroy", deck, method: :delete, data: {confirm: "本当に削除しますか？"}  %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>Members</h1>
<div>
  <% @members.each do |member| %>
  <div style="display:inline-block;vertical-align:top;width:200px;" >
    <div><img src=<%= member.img %>></div>
    <div><%= member.number %> <%= member.name %></div>
    <%= button_to "デッキから除く", deck_remove_member_path(:deck_id => member.id, :member_number => member.number), :remote => true %>
  </div>
  <% end %>
</div>

<h1>Musics</h1>
<div>
  <% @musics.each do |music| %>
  <div style="display:inline-block;vertical-align:top;width:200px;" >
    <div><img src=<%= music.img %>></div>
    <div><%= music.number %> <%= music.name %></div>
    <%= button_to "デッキから除く", deck_remove_music_path(:deck_id => music.id, :music_number => music.number), :remote => true %>
  </div>
  <% end %>
</div>

<br>

<%= form_tag decks_path, :method => :post do |f| %>
  <%= text_field_tag :name, params[:name] %>
  <%= submit_tag "確定" %>
<% end %>

app/views/decks/live.js.erb
$("#stage").html( '<%= j(render 'stage') %>');

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Back', decks_path %>

app/views/decks/setlist_open.js.erb
$("#stage").html( '<%= j(render 'stage') %>');

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<h1> デッキ名 : <%= @deck.name %> </h1>
<br>

<h1>Members</h1>
<div>
  <div style="display:inline-block;vertical-align:top;width:200px;" >
    <div><img src=<%= @start.img %>></div>
    <div><%= @start.number %> <%= @start.name %></div>
  </div>

  <% @members.each do |member| %>
  <div style="display:inline-block;vertical-align:top;width:200px;" >
    <div><img src=<%= member.img %>></div>
    <div><%= member.number %> <%= member.name %></div>
    <div><%= link_to "スタートにする", deck_to_start_path(id: @deck.id, deck_id: @deck.id, number: member.number), method: :post, class: "btn btn-default", type: :button %></div>
  </div>
  <% end %>
</div>

<h1>Musics</h1>
<div>
  <% @musics.each do |music| %>
  <div style="display:inline-block;vertical-align:top;width:200px;" >
    <div><img src=<%= music.img %>></div>
    <div><%= music.number %> <%= music.name %></div>
  </div>
  <% end %>
</div>

<div>
<%= link_to "対戦よろしくお願いします", battle_deck_path(@deck), class: "btn btn-default" %>
</div>

<br>
<%= link_to 'Edit', edit_deck_path(@deck), class: "btn btn-default" %> |
<%= link_to 'Back', decks_path, class: "btn btn-default"%>

app/views/decks/to_start.js.erb
$("#stage").html( '<%= j(render 'stage') %>');

app/views/decks/to_top.js.erb
$("#stage").html( '<%= j(render 'stage') %>');