config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'members#index'
  resources :cards
  resources :members do
    post :buy
  end
  resources :musics do
    post :buy
  end
  resources :decks do
    post :remove_member
    post :remove_music
    post :to_start
    post :draw, on: :collection
    post :back, on: :collection
    post :enter, on: :collection
    post :enter_from_top, on: :collection
    post :to_top, on: :collection
    post :to_bottom, on: :collection
    post :setlist_open, on: :collection
    post :live, on: :collection
    member do
      get :battle
      get :display
    end
  end

  post "/members/:id", to: "decks#add"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SICConfigurator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand">ラブライブ！スクコレデッキ管理システム</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "デッキ", decks_path %></li>
          <li><%= link_to "メンバー", members_path %></li>
          <li><%= link_to "楽曲", musics_path %></li>
        </ul>
      </div>
    </div>
    <p class="alert"><%= alert %></p>
    </br>

    <%= yield %>
    <% if user_signed_in? %>
      <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-warning" %></p>
    <% end %>
  </body>
</html>