config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'members#index'
  resources :cards
  resources :members do
    post :buy
  end
  resources :musics do
    post :buy
  end
  resources :decks do
    post :remove_member
    post :remove_music
    post :to_start
    post :draw, on: :collection
    post :back, on: :collection
    post :enter, on: :collection
    post :enter_from_top, on: :collection
    post :to_top, on: :collection
    post :to_bottom, on: :collection
    post :setlist_open, on: :collection
    post :live, on: :collection
    member do
      get :battle
      get :display
    end
  end

  post "/members/:id", to: "decks#add"
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :card, foreign_key: :number, primary_key: :number
  attr_accessor :count
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    # 検索用のセレクトボックスに表示する、名前一覧
    @name_list = Member.joins(:card).select("cards.name").order("cards.name").distinct
    @rarity_list = Member.select(:rarity).order(:rarity).distinct

    # 検索の実行
    @search_form
    if params[:search] == nil
      @search_form = MemberSearchForm.new
    else
      attr = params.require(:search).permit(:name, :rarity) # strong parameters
      @search_form = MemberSearchForm.new(attr)
    end
    @members = @search_form.search
    @members = @members.order("cards.number").page(params[:page])
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def buy
    session[:member] ||= Hash.new(0)
    session[:member][params[:member_number]] = params[:number].to_i
    pp session[:member]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.joins(:card).select("cards.*, members.*").find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.fetch(:member, {})
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

    <%= form_for @search_form, as: 'search', url: :members, html: {method: :get, class: "form-inline"} do |f| %>
      <div class="form-group">
        <%= f.label :name, "名前" %>
        <%= f.collection_select :name, @name_list, :name, :name, {:include_blank => true}, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.label :rarity, "レアリティ" %>
        <%= f.collection_select :rarity, @rarity_list, :rarity, :rarity, {:include_blank => true}, {class: "form-control"} %>
      </div>

      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>

<br>
<%= page_entries_info @members %>
<br>

<div>
  <% @members.each do |member| %>
    <div style="display:inline-block;vertical-align:top;width:200px;" >
      <%= link_to member do %>
        <div><img src=<%= member.img %>></div>
        <div><%= member.number%> <%= member.name %></div>
      <% end %>
      <%= form_tag member_buy_path(:member_id => member.id, :member_number => member.number), :action => :buy, :remote => true do %>
        <%= select_tag :number, options_for_select([0, 1, 2, 3, 4]) %>
        <%= submit_tag "デッキに追加", class: "btn btn-success" %>
      <% end %>
    </div>
  <% end %>
</div>

<%= will_paginate @members, :renderer => BootstrapPagination::Rails %>

<br>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<img src=<%= @member.img %>>

<p>
  <strong>カードID</strong>
  <%= @member.number%>
</p>

<p>
  <strong>カード名</strong>
  <%= @member.name%>
</p>

<p>
  <strong>フレーバーテキスト</strong>
  <%= @member.skill%>
</p>

<%= form_tag ({:controller => "decks", :action => "add"}) do %>
  <%= hidden_field_tag(:id, @member.id) %>
  <%= submit_tag("デッキに入れる") %>
<% end %>

<%= link_to 'Back', members_path, class: "btn" %>